[build]
  command = "CI=false npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "18", NPM_FLAGS = "--legacy-peer-deps --force" }

[build.environment]
  VITE_SUPABASE_URL = "${VITE_SUPABASE_URL}"
  VITE_SUPABASE_ANON_KEY = "${VITE_SUPABASE_ANON_KEY}"
  SUPABASE_SERVICE_ROLE_KEY = "${SUPABASE_SERVICE_ROLE_KEY}"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200